create table public.notebook_pages (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  page_number integer not null,
  title text not null default '',
  notes text not null default '',
  moves jsonb not null default '[]'::jsonb,
  position text not null default 'start',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  unique (user_id, page_number)
);

alter table public.notebook_pages enable row level security;

create policy "Users can view their own pages"
on public.notebook_pages
for select
to authenticated
using (auth.uid() = user_id);

create policy "Users can create their own pages"
on public.notebook_pages
for insert
to authenticated
with check (auth.uid() = user_id);

create policy "Users can update their own pages"
on public.notebook_pages
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "Users can delete their own pages"
on public.notebook_pages
for delete
to authenticated
using (auth.uid() = user_id);
